#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2
# #+BEAMER_THEME: Madrid
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)
     
#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \DeclareMathOperator{\atantwo}{atan2}
#+LaTex_HEADER: \def\ucolor{blue!80!black}
#+LaTex_HEADER: \def\ycolor{green!60!black}
#+LaTex_HEADER: \newcommand*{\incolor}[1]{\textcolor{\ucolor}{#1}}
#+LaTex_HEADER: \newcommand*{\outcolor}[1]{\textcolor{\ycolor}{#1}}


#+title: Frequency response
# #+date: 2021-06-29

* What do I want the students to understand?			   :noexport:
  - The Frequency response of LTI's
  - Bode-diagram
  - Connection between bode diagram and Nyquist plot

* Which activities will the students do?			   :noexport:
  1. Interpret Nyquist plots
  2. Draw simple Nyquis plots
  3. Draw simple Bode diagrams - Integrator, derivator, lead-filter, lag-filter


* Bode diagram

** Response of LTI systems to sinusoids
   \begin{center}
     \begin{tikzpicture}[scale = 0.8, node distance=20mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
     
     \node[coordinate] (refinput) {};
     \node[block, right of=refinput] (motor) {$G(s)$};
     \node[coordinate, right of=motor, node distance=20mm] (output) {};

     \draw[\ucolor, ->] (refinput) -- node[above, pos=0.3] (voltsignal) {$u$} (motor);
     \draw[\ycolor, ->] (motor) -- node[above, pos=0.5] (velsignal) {$y$} (output);
     \end{tikzpicture}
   \end{center}

   Let $\incolor{u(t) = \sin\omega_1 t}$. Then, after transients have died out,
   \[ \outcolor{y(t)}= \outcolor{|G(\omega_1)| \sin \big( \omega_1 t + \arg G(i\omega_1)\big)}. \]

*** Proof						:noexport:whiteboard:
    - complex exponential functions are eigen functions of LTIs:
      - u(t) = e^st, s=\sigma + i\omega, 
	u(t) = e^{(\sigma + i\omega) t} = e^{sigma t} e^{i\omega t}.
	|u(t)| = |e^{sigma t}||e^{i\omega t}| = |e^{\sigma t}|
	\arg u(t) = \arg e^{\sigma t} + \arg e^{i\omega t} = \omega t.

	Exercise!

	Signal u(t)=e^{st} been exciting the system since forever
      y(t) = (g * u) (t) = \int_{-\inft}^\infty g(\tau) u(t-\tau) d\tau
           = \int_0^\infty g(\tau) e^{s(t-\tau)}d\tau 
           = e^{st} \int_0^\infty g(\tau)e^{-s\tau} d\tau
           = e^{st} G(s)

     In particular s=i\omega
      


    In steps
    1. Complex sinusoids: \( x(t) = \mexp{i\omega t} = \cos (\omega t) + i\sin (\omega t) \) so 
       \( \sin (\omega t) = \impart{ \mexp{i \omega t} \)
    2. Phase shifted and amplified complex sinusoid: 
       \( ax(t) = a \mexp{i\omega t} = r \mexp{i\theta} \mexp{i\omega t} 
                = |a| \mexp{i \arg a} \mexp{i\omega t} = |a| \mexp{i(\omega t + \arg a} \) 
    3. \( y(t) = \impart{ ax(t) } = |a|\sin (\omega t + \arg a). \)
    4. Exercise: Given \( x(t) = \mexp{it} \). Draw \( y(t) = \impart{ ax(t) } \) for \( a = 2\mexp{-i\pi/2} \)
    5. Now consider LTI \( G(s) = \laplace{g(t)} = \int_0^\infty g(\tau) \mexp(-s\tau} d\tau \),
       where \(g(t)\) is the impulse response of the system.
       Input signal 
       \( u(t) = \sin (\omega t) = \impart{ \mexp{i\omega t} } \) since the beginning of times.
       Hints
       - Convolution : \( (g * f)(t) =  \eqdef \int_{-\infty}^{\infty} g(\tau) f(t-\tau) d\tau \)
       - Causality:  \( g(t) = 0, t<0 \) No response before the impulse happens. 
         The system cannot guess that an impulse will happen in the future.
       - Linearity of the \( \impart{.} \) operator: 
         \[ \int \impart{f(\tau)} d\tau = \impart{ \int f(\tau) d\tau } \]
       - Laplace: \int_0^\infty f(\tau) \mexp(-i\omega \tau) d\tau = F(s)|_{s=i\omega}
       \( Y(s) = G(s) U(s) \) or equivalently 
       \[ y(t) = (g * u) (t) \eqdef \int_{-\infty}^{\infty} g(\tau) u(t-\tau) d\tau
       =  \int_{-\infty}^{\infty} g(\tau) \impart { \mexp{i\omega (t-\tau)} } d\tau\]
       Since system is causal => \( g(t) = 0, t<0 \)
       \[ y(t) = \int_{0}^\infty g(\tau) \impart { \mexp{i\omega t} \mexp{-i\omega\tau} } d\tau
       = \impart{ \right( \int_{0}^\infty g(\tau) \mexp[-i\omega\tau} } d\tau\left) \mexp{i\omega t} 
       = \impart{ G(i\omega) \mexp{i\omega t} } 
       = \impart{ |G(i\omega)| \mexp{i \arg G(i\omega)} \mexp{i\omega t} }
       = |G(i\omega)| \sin ( \omega t + \arg G(i\omega) ) \]


** The Bode diagram
   
   \[ y(t) = \underbrace{|G(i\omega_1)|}_{\text{amplification}} \sin \big( \omega_1 t + \underbrace{\arg G(i\omega_1)}_{\text{phase shift}} \big) \]

   The Bode diagram shows the *magnitude* and *phase* of the transfer function evaluated on the positive imaginary axis. It thus contains all information about the steady-state response of the system to input signals of different frequency.


** Exercise: Reading the Bode diagram
   #+BEGIN_CENTER 
    \includegraphics[width=\linewidth]{../../figures/alias-example-bode-GC}
   #+END_CENTER
   which of the below responses *is not* compatible with the Bode diagram?

   #+BEGIN_CENTER 
    \includegraphics[width=\linewidth]{../../figures/example-bode-GC-timeseries}
   #+END_CENTER

*** Notes                                                          :noexport:
3: 4pi/pi s = 4 rad/s, gain \approx 1, phshift \approx -150, not quite completely out of phase. OK

Correct answer 2: Should have had an amplification, but plot shows attenuation.

** Specifications on the frequency properties of the closed-loop system

#+BEGIN_CENTER 
 \includegraphics[width=0.899\linewidth]{../../figures/spec-bode-closed-loop-new}
#+END_CENTER

** From loop gain to closed-loop gain
   #+begin_export latex
   \begin{center}
   \begin{tikzpicture}
  \tikzset{node distance=2cm, 
      block/.style={rectangle, draw, minimum height=12mm, minimum width=14mm},
      sumnode/.style={circle, draw, inner sep=2pt}        
  }

    \node[coordinate] (input) {};
    \node[sumnode, right of=input, node distance=20mm] (sum) {\tiny $\sum$};
    \node[block,right of=sum, node distance=30mm] (fb) {$F(s)$};
    \node[block,right of=fb, node distance=30mm] (plant) {$G(s)$};
    \node[coordinate, right of=plant, node distance=30mm] (output) {};
    \node[coordinate, right of=plant, node distance=22mm] (measure) {};
    \draw[->] (input) -- node[above, pos=0.2] {$y_{ref}(t)$} (sum);
    \draw[->] (sum) -- node[above] {$e(t)$} (fb);
    \draw[->] (fb) -- node[above] {$u(t)$} (plant);
    \draw[->] (plant) -- node[at end, above] {$y(t)$} (output);
    \draw[->] (measure) -- ++(0, -18mm) -| (sum) node[left, pos=0.96] {$-$};
    \draw[red] (3.8, -1) rectangle (9.4, 1.7);
    \node[red] at (8, 1.4) {$G_o(s)$};
    \end{tikzpicture}
  \end{center}
  #+end_export


\[ G_c(i\omega) = \frac{G(i\omega)F(i\omega)}{1 + G(i\omega)F(i\omega)} = \frac{G_o(i\omega)}{1 + G_o(i\omega)} \]
#+BEAMER: \pause

\[ |G_c(i\omega)| = \frac{|G_o(i\omega)|}{|1 + G_o(i\omega)|} = \frac{|G_o(i\omega)|}{|G_o(i\omega) - (-1)|} \]

#+BEAMER: \pause

*Keep the loop gain \(G_o(i\omega)\) away from -1!* 

*** Notes                                                          :noexport:

- Sketch two imaginary planes.
  - Mark imaginary axis s=iw
  - Map some points on imaginary axis through G_o(iw)
- Mark what |G_o| is: length of arrow from origin to G_o 
- Mark |G_o - 1|: length of arrow from 1 to G_o






** If \(G_o(i\omega_1) = -1\)

   \( G_o(i\omega_1) = -1 \), \(\quad |G_o(i\omega_1)| = 1\), \(\quad \arg G_o(i\omega_1) = -\pi\)

   #+begin_export latex
   \begin{center}
     \begin{tikzpicture}[node distance=22mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
    
       \node[coordinate] (input) {};
       \node[circle, fill, inner sep=1pt, right of=input, node distance=24mm] (sum) {};
       \node[circle, fill, inner sep=1pt, below of=sum, node distance=5mm] (sum2) {};
       \node[coordinate, below of=sum, node distance=2.5mm] (summid) {};
       \node[circle, fill, inner sep=1pt, right of=summid, node distance=5mm] (sum3) {};
       \node[block, right of=sum3, node distance=20mm] (plant)  {$G_o(s)$};
       \node[coordinate, right of=plant, node distance=40mm] (output) {};

       \draw[->] (input) -- node[above, pos=0.1, color=blue!80!black] {$u(t)=\sin(\omega_1 t)$} (sum);
       \draw[->] (plant) -- node[coordinate, pos=0.5] (measure) {} node[above, pos=0.3, anchor=south west, color=orange!80!red] {$y(t)=\sin\big(\omega_1 t -\pi\big) = -\sin(\omega_1 t)$} (output);
       \draw[->] (sum3) -- node[above] {} (plant);
       \draw[->] (measure) -- ++(0,-16mm) -| node[pos=0.95, left] {$-$} (sum2);
       \draw (sum) to (sum3);
     \end{tikzpicture}
   \end{center}
   #+end_export
   #+BEAMER: \pause
   Closed-loop transfer function: \(G_c(s) = \frac{G_o(s)}{1 + G_o(s)} \)
   \begin{tcolorbox}
   We want \[ 1 + G_o(i\omega) \neq 0, \quad \forall \omega \]
   If not, then the closed-loop system will have poles on the imaginary axis (in the s-domain). 
   \end{tcolorbox}

*** Notes                                                          :noexport:
There is a switch that lets us immediately shift the source of the input to the system, from an external source to a negative feedback signal.

Input is a sinusoid of a particular frequency w_1. Since the gain of the loop gain is -1 at this frequency, the sinusoid at the output will have the same amplitude and shifted in phase by pi. This means, of course, that the output is just the negative of the input signal.

In the feedback, the signal is negated. So if we switch, the input to the system will be the same as before. The output will also be the same, and we can see that the system will be oscillating at that particular frequency, with no external driving input.


** The Nyquist criterion                                           :noexport:
#+BEGIN_CENTER 
 \includegraphics[width=0.65\linewidth]{../../figures/implane-nyquist-contour-map}
#+END_CENTER

#+beamer: \pause

- Assume The loop gain \(G_o\) has \(P\) poles in the right half plane.
  - Count the number \(N\) with sign that the Nyquist curve encircles the point -1.

Recourses: 
[[https://youtu.be/sof3meN96MA][Brian Douglas (video)]]
[[https://lpsa.swarthmore.edu/Nyquist/NyquistStability.html][Swarthmore College (text)]]

** The simplified Nyquist criterion in the s-plane

#+BEAMER: \pause

#+BEGIN_CENTER 
 \includegraphics[width=0.65\linewidth]{../../figures/implane-nyquist-contour-map}
#+END_CENTER

#+BEAMER: \pause

\begin{tcolorbox}
If the open-loop system (the loop gain) is not unstable, i.e. $G_o(s)$ has no poles in the right-half plane, then the closed-loop system will be stable if the Nyquist curve \textbf{do not encircle the point \(s=-1\)}. The point $s=-1$ should stay on the left side of the Nyquist curve when we go along the curve from low to high frequencies.
\end{tcolorbox}

** Stability margins
#+BEGIN_CENTER 
 \includegraphics[width=0.38\linewidth]{../../figures/implane-nyquist-margins}
#+END_CENTER
   - Cross-over frequency: The frequency \(\omega_c\) for which \(|G_o(i\omega)| = 1\). 
   - Phase margin: The angle \(\varphi_m\) to the negative real axis for the point where the Nyquist curve intersects the unit circle. \[\varphi_m = \arg G_o(i\omega_c) - (-180\degree) = \arg G_o(i\omega_c) + 180\degree\]

*** Notes							   :noexport:
    The phase margin equals the  amount of extra negative phase that the loop gain can contribute before becoming unstable. For instance, assume delay of length T: F(s) = exp(-sT), which has phase 
    \arg F(i\omega) = \arg exp(i\omegaT) = \omega T
    If this is not accounted for in the loop gain
    \arg G_o(i\omega_c) - \phasemargin = -180, but
    \arg G_o^0 (i\omega_c) = \arg G_o(i\omega_c) - \omega_cT = -180 + \phasemargin - \omega_c T
    So for the closed-loop system to remain stable we must have
    \omega_c T = \phasemargin. 
** Stability margins
   
#+BEGIN_CENTER 
 \includegraphics[width=0.38\linewidth]{../../figures/implane-nyquist-margins}
#+END_CENTER
   - phase-cross-over frequency: The frequency \(\omega_p\) for which \(\arg G_o(i\omega) = -180\degree\). 
   - Gain margin: The gain $K=A$ that would make the Nyquist curve of \(KG_o(i\omega h)\) go through the point \(-1 + i0\). This means that \[ |G_o(i\omega_p h| = \frac{1}{A}. \]



   
* Freq-domain specs
** How to achieve the frequency-domain specifications

\[G_c(i\omega) = \frac{ G_o(i\omega)}{1 + G_o(i\omega)}\]

*Activity*
1) If \(Go(i\omega_1) = -0.5\) what is \(|G_c(i\omega_1)|\)?
2) If \(Go(i\omega_1) = -i\) what is \(|G_c(i\omega_1)|\)?

    
** Stability margins excercise
\begin{center}
  \includegraphics[width=.6\linewidth]{../../figures/bode-example-margin2.pdf}
\end{center}

*Activity* Determine the cross-over frequency \(\omega_c\), the phase cross-over frequency \(\omega_p\), the phase margin and the amplitude margin. 
** How to achieve the frequency-domain specifications
*** Problem statement
    :PROPERTIES:
    :BEAMER_col: 0.28
    :END:

    \[G_c(i\omega) = \frac{ G_o(i\omega)}{1 + G_o(i\omega)}\]

 \includegraphics[width=1.1\linewidth]{../../figures/spec-bode-closed-loop-new}

Which of the Bode plots to the right shows the correct loop gain \(G_o(i\omega)\)?

*** Plots
    :PROPERTIES:
    :BEAMER_col: 0.72
    :END:

#+BEGIN_CENTER 
 \includegraphics[width=1.02\linewidth]{../../figures/spec-bode-open-loop-new}
#+END_CENTER
    




