#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169, usenames, dvipsnames]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}
#+LaTex_HEADER:   \definecolor{ppc}{rgb}{0.1,0.1,0.6}
#+LaTex_HEADER:   \definecolor{iic}{rgb}{0.6,0.1,0.1}
#+LaTex_HEADER:   \definecolor{ddc}{rgb}{0.1,0.6,0.1}


#+title: Root locus
# #+date: 2020-09-01


* Repetition
** Block diagram algebra

\begin{center}
  \includegraphics[width=.6\linewidth]{../../figures/block-simple-feedback}
\end{center}

Transfer function from $r(t)$ to $y(t)$:
\[ \frac{Y(s)}{R(s)} = \frac{G(s)}{ 1+ G(s)}\]

#+BEAMER: \pause
*Mason's* gain formula: \(G_c(s) = \frac{Y(s)}{R(s)} = \frac{\sum_k T_k\Delta_k}{\Delta}\)

For simple systems with one loop only: \[G_c(s) = \frac{Y(s)}{R(s)} = \frac{\text{Forward path gain}}{1+\text{Loop gain}}\]




** Block diagram algebra

 *Activity* Pair the block-diagram with the correct closed-loop transfer function!


#+ATTR_LATEX:  :center :environment longtable :align cccc
| \textcolor{red}{A}                                                       | \textcolor{red}{B}                                                        | \textcolor{red}{C}                                                        |  \textcolor{red}{D}                                                       |
| \includegraphics[width=3cm]{../../figures/block-simple-control-feedback} | \includegraphics[width=3cm]{../../figures/block-simple-control-feedback2} | \includegraphics[width=3cm]{../../figures/block-simple-control-feedback3} | \includegraphics[width=3cm]{../../figures/block-simple-control-feedback4} |


#+ATTR_LATEX:  :center :environment longtable :align cccc
| \textcolor{blue!80!black}{I}                     | \textcolor{blue!80!black}{II}                              | \textcolor{blue!80!black}{III}                      |                                                   \textcolor{blue!80!black}{IV}    |
| \( \frac{Y(s)}{R(s)}=\frac{G(s)F(s)}{1 + G(s)}\) | \(\quad \frac{Y(s)}{R(s)}=\frac{G(s)}{1 + G(s)F(s)}\quad\) | \(\frac{Y(s)}{R(s)}=\frac{1}{1 + G(s)F(s)}\)        | \(\frac{Y(s)}{R(s)}=\frac{G(s)F(s)}{1 + G(s)F(s)}\) |


*** Notes                                                          :noexport:
Solution

A - IV
B - II
C - I
D - III



* Proportional control of the DC motor

** The DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-DC-feedback-white}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \def\ggain{200}
     \def\Tcnst{0.1}
     \begin{tikzpicture}
       \begin{axis}[
       width=7cm,
       height=6cm,
       grid = both,
       xlabel = {Time [s]},
       ylabel = {Ang vel [rad/s]},
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2, xmax=2,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=-0.2:2, samples=100] {(x>0)*\ggain*(1 - exp(-(x/\Tcnst)))}; 
      \end{axis}
     \end{tikzpicture}
    \end{center}


#+BEAMER: \pause

*Activity* What is the angle (approximately) rotated by the motor after 0.1s starting from still?
*** Notes                                                          :noexport:
Triangle a = 130/2 * 0.1 = 13/2 = 6.5 rad

Later normalized motor 0.4*20 = <8 rad
** The normalized DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-normalized-DC-feedback-white}
    \end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \def\ggain{1}
     \def\Tcnst{1}
     \begin{tikzpicture}
       \begin{axis}[
       width=7cm,
       height=6cm,
       grid = both,
       xlabel = {Time [$\tau$]},
       ylabel = {Ang vel [20 rad/$\tau$], angle [20 rad]},
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -2, xmax=20,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=-2:20, samples=100] {(x>0)*\ggain*(1 - exp(-(x/\Tcnst)))};
	 \addplot [thick, red!60!black, no marks, domain=-0.2:5, samples=100] {(x>0)*\ggain*(x + exp(-(x/\Tcnst)) -1)};
       \end{axis}
     \end{tikzpicture}
    \end{center}

    #+BEAMER: \pause
    *Activity* What is the settling time (approximately) for the velocity (in \(\tau\) and in seconds)?


** Proportional control of the normalized DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-DC-feedback}
    \end{center}

#+BEAMER: \pause 
*** plot
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \def\ggain{1}
     \def\Tcnst{1}
     \begin{tikzpicture}
       \begin{axis}[
       width=7cm,
       height=6cm,
       grid = both,
       xlabel = {Time [$\tau$]},
       ylabel = {Angle [20 rad]},
       title = {$K=1$},
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -2, xmax=20,
       minor y tick num=4,
       minor x tick num=4,
       every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, black, no marks, domain=-2:20, samples=200] {x>0};
	 \addplot [thick, red!60!black, no marks, domain=-0.2:20, samples=100] {(x>0)*(1 - (exp(-x/2)* (sqrt(3)* cos(deg((sqrt(3)* x)/2)) + sin(deg((sqrt(3)* x)/2))))/sqrt(3))};
       \end{axis}
     \end{tikzpicture}
    \end{center}


    #+BEAMER: \pause
    *Activity* What is the overshoot (in percent) and rise time (in seconds)?
    


** Proportional control of the normalized DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-DC-feedback}
    \end{center}

*** plot
:PROPERTIES:
:BEAMER_col: 0.5
:END:

Closed-loop transfer function:
\[ G_c(s) = \frac{K}{s(s+1) + K}\]

Characteristic equation:
\[ s^2 + s + K = 0\]

*Activity* Solve the characteristic equation!

*** Notes                                                          :noexport:
s = -1/2 +/- 1/2 sqrt(1 - 4K)

Case 1: 0 < K < 1/4  Real-valued poles symmetric about -1/2
Case 2: (corner case) K=1/4: two poles in -1/2
Case 3: K>1/4 Complex conj poles
        s = -1/2 +/- i/2 sqrt(4K-1)
        Real part stays the same. Imaginary part goes out towards infinity on lines
	parallel to imaginary axis.
	
* The root locus diagram

** Root locus

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-rlocus}
    \end{center}

    *How do the closed-loop poles depend on \(K\)?*

** PI-control of the tank example                                  :noexport:
*** text
    :PROPERTIES:
    :BEAMER_col: 0.25
    :END:
    Root locus wrt $K_i$ with $K_p=2$.

*** graphics
    :PROPERTIES:
    :BEAMER_col: 0.75
    :END:

#+BEGIN_CENTER 
 \includegraphics[width=0.6\linewidth]{../figures/PItank}
#+END_CENTER

** Root locus definition
Let
\[\begin{cases} P(s)&=s^n+a_1s^{n-1}+\dots+a_n = (s-p_1)(s-p_2)\cdots(s-p_n)\\ 
Q(s)&=s^m+b_1s^{m-1}+\dots+b_m=(s-q_1)(s-q_2)\cdots(s-q_m) \end{cases},\ \ \ n\ge m \]
The root locus shows how the roots to the equation
\begin{equation}
\label{eq:P(s)+KQ(s)=0}
P(s)+K\cdot Q(s)=0,\ \ \ 0\le K<\infty
\end{equation}
 depend on the parameter $K$. The root locus consists of the set of all points in the complex plane that are roots to \eqref{eq:P(s)+KQ(s)=0} for some non-negative value of $K$.

** Characteristics of the root locus
The polynomial \( P(s)+KQ(s)=0 \) above will always have $n$ roots. Each gives a /branch/ in the root locus. Since the polynomials $P(s)$ and $Q(s)$ have real-valued coefficients, all roots are either real or complex-conjugated pairs. This means that the root locus is /symmetric about the real axis./ Other characteristics
- Start points - marked by crosses
- End points - marked  by circles
- Asymptotes
- Pieces of the real axis

** Start- and end points
- Start points ::  These are the $n$ roots of \(P(s) + KQ(s)\) for $K=0$, i.e. the roots of $P(s)$. These are the open-loop poles, and are marked with crosses '\(\times\)'
- End points :: These are the $m$ (finite) roots of \(P(s)+KQ(s)\) when $K\to\infty$, and are hence the roots of $Q(s)$. The end points are marked with circles '\(\circ\)'

** The real axis

Those parts of the real axis that have an *odd number* of real-valued start- or end points to the right (including multiplicity) belong to the root locus. 

*** Explanation							   :noexport:
The reason is as follows. Write the equation to solve
\[\frac{P(s)}{Q(s)} = -K, \quad \text{and factorize to get} \]
\[\frac{(s-p_1)(s-p_2) \cdots (s-p_n)}{(s-q_1)(s-q_2)\cdots(s-q_m)} = -K\]
The values $p_1, \ldots, p_n$ are the start points and $q_1, \ldots q_m$ are the end points. Sufficiently far to the right on the real axis all the factors will be positive (or have postive real part). The fraction is positive and so the equation does not have a solution. Hence, the part of the real axis to the right of all real-valued start- and end points is *not* part of the root locus. As $s$ decreases, the fraction on the left will change sign every time one passes a real-valued start- or end point.

# The branches of the root locus cannot cross, so when two branches meet (in a double root), the branches must "break out" in the complex plane. This happens at 90 degrees.


** Asymptotes							   :noexport:
With $n$ starting points and $m$ end points, then $m$ of the branches will go to end points. The rest will go out towards infinity along $n-m$ asymptotes. The asymptotes go out symmetrically from a point on the real axis. 

*** Not this time						   :noexport:
Write the equation \(P(s) + KQ(s) = 0\) as
\[\frac{s^n + a_1s^{n-1} + \cdots + a_n}{s^m + b_1s^{m-1} + \cdots b_m} = -K\]
Do polynomial division to obtain
\[ s^{n-m} + \frac{(a_1-b_1)s^{n-1} + \cdots}{s^m + b_1s^{m-1} + \cdots + b_m} = -K \]
For large values of $s$, along the asymptotes, we only consider the highest powers of $s$. So the asymptotes are given by 
\[ s^{n-m} + (a_1 - b_1)s^{n-m-1} = -K \]
\begin{equation*}
\begin{split}
 & \frac{s^{n-m}(s^m + b_1s^{m-1} + \cdots + b_m + (a_1-b_1)s^{m-1} + (a_2 -b_2)s^{m-2} + \cdots + \(a_m-b_m) + \cdots}{s^m + b_1s^{m-1} + \cdots + b_m}\\
 & = -K
\end{split}
\end{equation*}

** Asymptotes, contd						   :noexport:
For large $s$, we can simplify further by writing
\[ s^{n-m} + (a_1 - b_1)s^{n-m-1} \approx \left(s + \frac{a_1 - b_1}{n-m}\right)^{n-m} \]
to get the equation
\[ \left(s + \frac{a_1 - b_1}{n-m}\right)^{n-m} = -K \]
for the asymptotes.

To understand the approximation, note that 
\[ (s+\frac{c}{3})^3 = s^3 + cs^2 + c^2s/3 + c^3/27 \]

** Asymptotes, directions					   :noexport:

\[ \left(s + \frac{a_1 - b_1}{n-m}\right)^{n-m} = -K. \]
For large values of $s$, way out from the origin of the complex plane, we can neglect the constant term to get
\[ s^{n-m} = -K \]
To find the direction of the asymptotes, take the argument of both sides.
\[ \arg s^{n-m} = (n-m) \arg s =  \arg (-K) = \pi + k2\pi, \; k \in \mathbb{Z} \]
This gives the directions
\[ \theta_k = \arg s = \frac{(2k+1)\pi}{n-m}, \; k \in \mathbb{Z} \]

** Asymptotes, directions
The directions of the asymptotes are given by the expression
\[ \theta_k = \arg s = \frac{(2k+1)\pi}{n-m}, \; k \in \mathbb{Z} \]
Example: 6 start points and 3 end points gives \(n-m = 6-3 = 3 \) and the directions

*** math
    :PROPERTIES:
    :BEAMER_col: 0.35
    :END:

\[ \theta = \begin{cases} \frac{\pi}{3}, & k=0\\ \pi, & k=1\\ -\frac{\pi}{3}, & k=-1 \end{cases}. \]

*** fig	
    :PROPERTIES:
    :BEAMER_col: 0.65
    :END:
#+BEGIN_CENTER 
 \includegraphics[width=0.8\linewidth]{root-locus-ex-3asymptotes-crop}
#+END_CENTER

** Asymptotes, intersection with the real axis			   :noexport:
 Consider again 
 \[ \left(s + \frac{a_1 - b_1}{n-m}\right)^{n-m} = -K \]
The intersection with the real axis is found for $K=0$, which leads to the equation
\[ \left(s + \frac{a_1 - b_1}{n-m}\right)^{n-m} = 0 \]
with solution
\[ s = \frac{ -a_1 + b_1}{n-m}. \]

The coefficients $a_1$ and $b_1$ are related to the roots of $P(s)$ and $Q(s)$, respectively, as
\begin{align*}
a_1 &= - \sum_{i=0}^n p_i\\
b_1 &= - \sum_{i=0}^m q_i
\end{align*}

#+BEAMER: \pause

*Activity* Calculate the intersection for the follcase \(p = \{0, -1,  -3\}\), \(q = \{-2\}\)

** Asymptotes, intersection with the real axis 
# The directions:
# \[ \theta_k = \frac{(2k+1)\pi}{n-m}, \; k \in \mathbb{Z} \]

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

\[ ip = \frac{ \sum_{i=1}^n p_i - \sum_{i=1}^m q_i}{n-m}, \]
where $\{p_i\}$ are the starting points (open-loop poles) and $\{q_i\}$ are the end points (open-loop zeros). 

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

   \pgfmathsetmacro{\impart}{sqrt(3)/2}
    \begin{center}
   \small
      \begin{tikzpicture}[scale=1.4, block/.style={draw, minimum width=12mm, minimum height=8mm},]
      \draw[->] (-4, 0) -- node[right, pos=1] {Re} (0.5, 0);
      \draw[->] (0, -1.3) -- node[right, pos=0.96] {Im} (0, 1.3);
      \draw (-1, 0) -- ++(0,-0.2) node[below] {-1};
      \draw (-2, 0) -- ++(0,-0.2) node[below] {-2};
      \draw (-3, 0) -- ++(0,-0.2) node[below] {-3};
      \node[red, ] at (0,0) {\large $\times$};
      \node[red] at (-1, 0) {\large $\times$};
      \node[red] at (-3, 0) {\large $\times$};
      \node[green!80!black,] at (-2, 0) {\large $\circ$};
      %\node[green!80!black] at (-0.5, 0) {\large $\circ$};

      \end{tikzpicture}

    \end{center}


*** Notes                                                          :noexport:

For instance p = {0, -1, -3}, q = {-2}


* Examples

** Examples

** Motor driving an elastic shaft

#+begin_export latex
    \small
    \begin{center}
      \includegraphics[width=0.4\linewidth]{../../figures/elastic-shaft.jpg}

      \begin{tikzpicture}[scale=0.7, transform shape, block/.style={draw, minimum width=12mm, minimum height=8mm},]
        \node[block] (plant) {$G(s)$};
        \node[circle, draw, inner sep=1pt, right of=plant, node distance=2cm] (sum) {\tiny $\Sigma$};
        \node[block, above of=sum, node distance=2cm] (load) {$H(s)$};
        \draw[->] (plant) ++ (-2cm, 0) -- node[very near start, above] {$T_i(t)$} (plant);
        \draw[->] (load) ++ (0,1cm) -- node[very near start, left] {$T_l(t)$} (load);
        \draw[->] (plant) -- (sum);
        \draw[->] (load) -- (sum);
        \draw[->] (sum) -- node[very near end, above] {$\theta_2(t)$} ++(2cm, 0);
      \end{tikzpicture}

      \end{center}

   \begin{align*}
   \Theta_2(s) &= \underbrace{\frac{k + bs}{s^2(J_1J_2s^2 + bs + k)}}_{G(s)}T_i(s) \underbrace{- \frac{J_1s^2 + bs + k}{s^2(J_1J_2s^2 + bs + k)}}_{H(s)}T_l(s)
      \end{align*}
#+end_export

** Motor driving an elastic shaft

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

PD-control

    \begin{center}
      \begin{tikzpicture}[scale=0.9, transform shape, block/.style={draw, minimum width=12mm, minimum height=8mm},]
        \node[block] (plant) {$\frac{s+1}{s(s^2 + s + 1)}$};
        \node[block, left of=plant, node distance=3cm] (pd) {$K(2s + 1)$};
        \node[circle, draw, inner sep=1pt, left of=pd, node distance=2cm] (sum) {\tiny $\Sigma$};
        \node[coordinate, left of=sum,] (input) {};
        \draw[->] (input) -- node[very near start, above] {$r$} (sum);
        \draw[->] (sum) -- node[ above] {$e$} (pd);
        \draw[->] (pd) -- node[above] {$T_i$} (plant);
        \draw[->] (plant) -- node[coordinate] (meas) {}
                node[very near end, above] {$v_2$} ++(2cm, 0);
        \draw[->] (meas) -- ++(0, -15mm) -| node[left, pos=0.9] {$-$} (sum);
      \end{tikzpicture}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

   \pgfmathsetmacro{\impart}{sqrt(3)/2}
    \begin{center}
   \small
      \begin{tikzpicture}[scale=1.4, block/.style={draw, minimum width=12mm, minimum height=8mm},]
      \draw[->] (-2, 0) -- node[right, pos=1] {Re} (0.5, 0);
      \draw[->] (0, -1.3) -- node[right, pos=0.96] {Im} (0, 1.3);
      \draw (0,\impart) -- ++(0.2, 0) node[right] {$i\frac{\sqrt{3}}{2}$};
      \draw (0,-\impart) -- ++(0.2, 0) node[right] {$-i\frac{\sqrt{3}}{2}$};
      \draw (-0.5, 0) -- ++(0,-0.2) node[below] {-0.5};
      \draw (-1, 0) -- ++(0,-0.2) node[below] {-1};
      %\node[red, ] at (0,0) {\large $\times$};
      %\node[red] at (-0.5, \impart) {\large $\times$};
      %\node[red] at (-0.5, -\impart) {\large $\times$};
      %\node[green!80!black,] at (-1, 0) {\large $\circ$};
      %\node[green!80!black] at (-0.5, 0) {\large $\circ$};

      \end{tikzpicture}

    \end{center}

    *Activity* Indicate the start- and end points.
    
*** Notes                                                          :noexport:
Startpoints: n=3 {0, -1/2 + i sqrt(3)/2, -1/2 - i sqrt(3)/2}
End points: n=2 {-1/2, -1}

Asymptote: -180

Odd rule



** Motor driving an elastic shaft

\begin{center}
  \includegraphics[width=.7\linewidth]{../../figures/shaft-rlocus}
\end{center}

** Harmonic oscillator

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

P-control

    \begin{center}
      \begin{tikzpicture}[scale=0.9, transform shape, block/.style={draw, minimum width=12mm, minimum height=8mm},]
        \node[block] (plant) {$\frac{1}{s^2 + 1}$};
        \node[block, left of=plant, node distance=2cm] (pd) {$K$};
        \node[circle, draw, inner sep=1pt, left of=pd, node distance=2cm] (sum) {\tiny $\Sigma$};
        \node[coordinate, left of=sum,] (input) {};
        \draw[->] (input) -- node[very near start, above] {$r$} (sum);
        \draw[->] (sum) -- node[ above] {$e$} (pd);
        \draw[->] (pd) -- node[above] {} (plant);
        \draw[->] (plant) -- node[coordinate] (meas) {}
                node[very near end, above] {$y$} ++(2cm, 0);
        \draw[->] (meas) -- ++(0, -15mm) -| node[left, pos=0.9] {$-$} (sum);
      \end{tikzpicture}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

   \pgfmathsetmacro{\impart}{sqrt(3)/2}
    \begin{center}
   \small
      \begin{tikzpicture}[scale=1.4, block/.style={draw, minimum width=12mm, minimum height=8mm},]
      \draw[->] (-3, 0) -- node[right, pos=1.02] {Re} (0.5, 0);
      \draw[->] (0, -1.3) -- node[right, pos=0.96] {Im} (0, 1.3);
      \draw (0,\impart) -- ++(0.2, 0) node[right] {$i$};
      \draw (0,-\impart) -- ++(0.2, 0) node[right] {$-i$};
      %\draw (-0.5, 0) -- ++(0,-0.2) node[below] {-0.5};
      \draw (-1, 0) -- ++(0,-0.2) node[below] {-1};
      %%\node[red, ] at (0,0) {\large $\times$};
      %\node[red] at (-0.5, \impart) {\large $\times$};
      %\node[red] at (-0.5, -\impart) {\large $\times$};
      %\node[green!80!black,] at (-1, 0) {\large $\circ$};
      %\node[green!80!black] at (-0.5, 0) {\large $\circ$};

      \end{tikzpicture}

    \end{center}

  *Activity* Indicate the start- and end points, and the asymptotes.
  
*** Notes                                                          :noexport:
Startpoints: n=3 {i, -i, -2}
End points: n=1 {-1/2}

Asymptote: intersection (\sum p_i - \sum q_1)/2 = (-2 + 1/2)/2 = -3/4

Odd rule



** Harmonic oscillator

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

Lead-compensator

    \begin{center}
      \begin{tikzpicture}[scale=0.9, transform shape, block/.style={draw, minimum width=12mm, minimum height=8mm},]
        \node[block] (plant) {$\frac{1}{s^2 + 1}$};
        \node[block, left of=plant, node distance=2cm] (pd) {$K\frac{2s + 1}{s+2}$};
        \node[circle, draw, inner sep=1pt, left of=pd, node distance=2cm] (sum) {\tiny $\Sigma$};
        \node[coordinate, left of=sum,] (input) {};
        \draw[->] (input) -- node[very near start, above] {$r$} (sum);
        \draw[->] (sum) -- node[ above] {$e$} (pd);
        \draw[->] (pd) -- node[above] {} (plant);
        \draw[->] (plant) -- node[coordinate] (meas) {}
                node[very near end, above] {$y$} ++(2cm, 0);
        \draw[->] (meas) -- ++(0, -15mm) -| node[left, pos=0.9] {$-$} (sum);
      \end{tikzpicture}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

   \pgfmathsetmacro{\impart}{sqrt(3)/2}
    \begin{center}
   \small
      \begin{tikzpicture}[scale=1.4, block/.style={draw, minimum width=12mm, minimum height=8mm},]
      \draw[->] (-3, 0) -- node[right, pos=1.02] {Re} (0.5, 0);
      \draw[->] (0, -1.3) -- node[right, pos=0.96] {Im} (0, 1.3);
      \draw (0,\impart) -- ++(0.2, 0) node[right] {$i$};
      \draw (0,-\impart) -- ++(0.2, 0) node[right] {$-i$};
      \draw (-0.5, 0) -- ++(0,-0.2) node[below] {-0.5};
      \draw (-2, 0) -- ++(0,-0.2) node[below] {-2};
      %%\node[red, ] at (0,0) {\large $\times$};
      %\node[red] at (-0.5, \impart) {\large $\times$};
      %\node[red] at (-0.5, -\impart) {\large $\times$};
      %\node[green!80!black,] at (-1, 0) {\large $\circ$};
      %\node[green!80!black] at (-0.5, 0) {\large $\circ$};

      \end{tikzpicture}

    \end{center}

  *Activity* Indicate the start- and end points, and the asymptotes.
  
*** Notes                                                          :noexport:
Startpoints: n=3 {i, -i, -2}
End points: n=1 {-1/2}

Asymptote: intersection (\sum p_i - \sum q_1)/2 = (-2 + 1/2)/2 = -3/4

Odd rule



** Pair the root locus plots with the correct transfer function
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.3
:END:

   \begin{align*}
   G_1(s) &= K\frac{s+2}{s(s+4)}\\ G_2(s) &= K\frac{s+2}{s(s+4)(s+8)}\\
   G_3(s) &= K\frac{s+2}{s^2(s+4)}\\ G_4(s) &= K \frac{1}{s^2(s+4)}.
   \end{align*}

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.7
:END:

   
   #+BEGIN_CENTER 
    \includegraphics[width=1.0\linewidth]{../../figures/rlocus_2x2-crop}
   #+END_CENTER


