#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169, usenames, dvipsnames]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}
#+LaTex_HEADER:   \definecolor{ppc}{rgb}{0.1,0.1,0.6}
#+LaTex_HEADER:   \definecolor{iic}{rgb}{0.6,0.1,0.1}
#+LaTex_HEADER:   \definecolor{ddc}{rgb}{0.1,0.6,0.1}


#+title: Design of control systems
# #+date: 2020-09-01

* What do I want the students to understand?			   :noexport:
  - Course structure
  - Feedback control
  - Performance requirements

* Which activities will the students do?			   :noexport:
  - Block diagram feedback system
  - Sensitivity and complementary sensitivity
  - Root locus simple case

* Course content

** Feedback control

#+begin_export latex
\begin{center}
\begin{tikzpicture}[node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
  \node[sumnode, right of=input] (sum) {};
   \node[block, right of=sum,] (lti) {Controller};
   \node[block, right of=lti, node distance=30mm] (lti2) {Plant};
   \node[coordinate, right of=lti2, node distance=30mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$r(t)$}  (sum);
   \draw[->] (sum) -- node[ above] {}  (lti);
   \draw[->] (lti) -- node[ above] {$u(t)$}  (lti2);
   \draw[->] (lti2) -- node[coordinate] (meas) {} node[near end, above] {$y(t)$} (output);
   \draw[->] (meas) -- ++(0, -14mm) -| node[left, pos=0.96] {$-$} (sum);
 \end{tikzpicture}
\end{center}

#+end_export

*** Notes                                                          :noexport:

- Examples:
  | Input                     | Output                               |
  |---------------------------+--------------------------------------|
  | Torque in motor           | Angle of arm in robot manipulator    |
  | Voltage in motor armature | Angular velocity of motor            |
  | Thrust from rockets       | Position and orientation of satelite |
  | Opening of a valve        | Level in a tank                      |
  | Flow of steam             | Temperature in a tank reactor        |
  | Position of fuel rods     | Heat generated in a nuclear reactor  |


** Feedback control systems are ubiquitous

\begin{center}
  \includegraphics[width=.6\linewidth]{../../figures/PnID-ex.png}
\end{center}

*** Notes                                                          :noexport:

- Part in a food-processing plant.
- Type of diagram: Piping and Instrumentation Diagram
- Tank providing a flow of warm, sweat fluid.
- Valves, heating jacket.
- Q: How many feedback loops?


** Feedback control systems


#+begin_export latex
\begin{center}
\begin{tikzpicture}[scale = 0.7, node distance=20mm,
                    block/.style={rectangle, draw, minimum width=15mm, inner sep=3mm},
                    sumnode/.style={circle, draw, inner sep=3pt}]
  \node[coordinate] (input) {};
  \node[sumnode, right of=input] (sum) {};
   \node[block, right of=sum,] (lti) {Controller};
   \node[block, right of=lti, node distance=30mm] (lti2) {Plant};
   \node[coordinate, right of=lti2, node distance=30mm] (output) {};
   \draw[->] (input) -- node[near start, above] {$r(t)$}  (sum);
   \draw[->] (sum) -- node[ above] {}  (lti);
   \draw[->] (lti) -- node[ above] {$u(t)$}  (lti2);
   \draw[->] (lti2) -- node[coordinate] (meas) {} node[near end, above] {$y(t)$} (output);
   \draw[->] (meas) -- ++(0, -14mm) -| node[left, pos=0.96] {$-$} (sum);
 \end{tikzpicture}
\end{center}

#+end_export

*Controller design:* Determine a feedback controller such that the controlled system performs according to given *performance specifications*. 

*** Notes                                                          :noexport:

What is *good performance*?


** The problem situation
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

\begin{center}
  \includegraphics[width=.94\linewidth]{../../figures/mars-rover-curiosity-vehicle-cosmos.jpg}
\end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:
\begin{center}
  \includegraphics[width=.94\linewidth]{../../figures/mars.nasa.jpeg}
\end{center}


- Mass 900 kg
- Six wheels, each with an electric motor
- Front- and rear-wheel steering 
- Rocker-bogie suspension system

*** Notes                                                          :noexport:

- Curiosity rover
- Operating on mars for more than 10 years.
- Weighs close to 1t
- Six wheels, each with a DC motor 20W
- 0.9*6*20W = 108W acc 1t to 1 m/s:
  - Ek = 1/2 m v^2 = 0.5 * 900 * 1 = 450 J
  - P = dE/dt => \approx P_max = \Delta E / \Delta T => \Delta T = \Delta E / P_max = 450 J / (108) J/s \approx 4.2s
- P in  = P out, P = T*\omega, T_out * w_out = T_in * w_in => T_out/T_in = w_in/w_out = g_r
  g_r = T_out / T_in = 6 Nm / 30e-3 Nm = 1000 * 6/30 = 100 * 60/30 = 200:1
- 
- 

** The problem situation

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/curiosity-wheel.jpg}
    \end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

#+BEAMER: \pause

    \begin{center}
    \includegraphics[width=\linewidth]{../../figures/electric-drive-block.png}
    \end{center}


**** Notes                                                         :noexport:
- One motor in the hub of each wheel
- Electric drive
  - Motor
  - Sensors
  - Controller
  - Power electronics
  - Power source
    - On rover: Battery + Nuclear Thermo generator (Plutoneum source)
  - 

* Much content                                                     :noexport:
** MR2023 Modelación y automatización

\begin{center}
  \includegraphics[width=.4\linewidth]{../../figures/DB-content-1.png}
  \includegraphics[width=.4\linewidth]{../../figures/DB-content-2.png}
\end{center}

** MR2025 Design of control systems
\begin{center}
  \includegraphics[width=.36\linewidth]{../../figures/DB-content-3.png}
\end{center}

* Feedback, sensitivity and complementary sensitivity

** Block diagram algebra

\begin{center}
  \includegraphics[width=.6\linewidth]{../../figures/block-simple-feedback}
\end{center}

Transfer function from $r(t)$ to $y(t)$:
\[ \frac{Y(s)}{R(s)} = \frac{G(s)}{ 1+ G(s)}\]


** Block diagram algebra

 *Activity* Pair the block-diagram with the correct closed-loop transfer function!


#+ATTR_LATEX:  :center :environment longtable :align cccc
| \textcolor{red}{A}                                                       | \textcolor{red}{B}                                                        | \textcolor{red}{C}                                                        |  \textcolor{red}{D}                                                       |
| \includegraphics[width=3cm]{../../figures/block-simple-control-feedback} | \includegraphics[width=3cm]{../../figures/block-simple-control-feedback2} | \includegraphics[width=3cm]{../../figures/block-simple-control-feedback3} | \includegraphics[width=3cm]{../../figures/block-simple-control-feedback4} |


#+ATTR_LATEX:  :center :environment longtable :align cccc
| \textcolor{blue!80!black}{I}                     | \textcolor{blue!80!black}{II}                              | \textcolor{blue!80!black}{III}                      |                                                   \textcolor{blue!80!black}{IV}    |
| \( \frac{Y(s)}{R(s)}=\frac{G(s)F(s)}{1 + G(s)}\) | \(\quad \frac{Y(s)}{R(s)}=\frac{G(s)}{1 + G(s)F(s)}\quad\) | \(\frac{Y(s)}{R(s)}=\frac{1}{1 + G(s)F(s)}\)        | \(\frac{Y(s)}{R(s)}=\frac{G(s)F(s)}{1 + G(s)F(s)}\) |


*** Notes                                                          :noexport:
Solution

A - IV
B - II
C - I
D - III


* Control systems specifications

** Feedback control system                                         :noexport:

\begin{center}
  \includegraphics[width=.3\linewidth]{../../figures/curiosity-wheel.jpg}
  \includegraphics[width=.6\linewidth]{../../figures/electric-drive-block.png}
\end{center}


** Performance requirements 

   \begin{center}
     \begin{tikzpicture}[scale = 0.8, node distance=20mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
     
     \node[coordinate] (refinput) {};
     \node[block, right of=refinput] (motor) {$G_c(s)$};
     \node[coordinate, right of=motor, node distance=20mm] (output) {};

     \draw[->] (refinput) -- node[above, pos=0.3] (voltsignal) {$r(t)$} (motor);
     \draw[->] (motor) -- node[above, pos=0.5] (velsignal) {$y(t)$} (output);
     \end{tikzpicture}
   \end{center}


** Performance requirements - time domain
\begin{center}
  \includegraphics[width=.8\linewidth]{../../figures/step-response-specifications}
\end{center}

*** Notes                                                            :noexport:

PO = (ymax - yf)/yf * 100


** Performance requirements - time domain

 *Activity* Does the system satisfy the requirements?

*** Text
:PROPERTIES:
:BEAMER_col: 0.3
:END:

 | Rise time | < 1.5s |
 | Overshoot | < 18% |

 
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.7
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/second-order-response-example}
    \end{center}

*** Notes                                                            :noexport:

Each vert div 0.05,
Each hor div 0.5,
Overshoot, PO = (1.17-1)/1 * 100 = 17%

t_10 = 0.5
t_90 = 2.2

t_r = t_90 - t_10 = 2.2 - 0.5 = 1.7 s

** Performance requirements - frequency domain

** Response of LTI systems to sinusoids
   \begin{center}
     \begin{tikzpicture}[scale = 0.8, node distance=20mm, block/.style={rectangle, draw, minimum width=15mm}, sumnode/.style={circle, draw, inner sep=2pt}]
     
     \node[coordinate] (refinput) {};
     \node[block, right of=refinput] (motor) {$G_c(s)$};
     \node[coordinate, right of=motor, node distance=20mm] (output) {};

     \draw[->] (refinput) -- node[above, pos=0.3] (voltsignal) {$r(t)$} (motor);
     \draw[->] (motor) -- node[above, pos=0.5] (velsignal) {$y(t)$} (output);
     \end{tikzpicture}
   \end{center}

   Let $r(t) = \sin\omega_1 t$. Then, after transients have died out,
   \[ y(t) = |G_c(i\omega_1)| \sin \big( \omega_1 t + \arg G_c(i\omega_1)\big). \]


** The Bode diagram shows the frequency properties of a dynamical system

\small

   \[ y(t) = \underbrace{|G_c(i\omega_1)|}_{\text{amplification}} \sin \big( \omega_1 t + \underbrace{\arg G_c(i\omega_1)}_{\text{phase shift}} \big) \]


\begin{center}
  \includegraphics[width=.9\linewidth]{../../figures/bode-closed-loop-example-responses}
\end{center}


** Performance requirements - frequency domain

\begin{center}
  \includegraphics[width=.8\linewidth]{../../figures/spec-bode-closed-loop-new}
\end{center}

*** Notes                                                          :noexport:


** Performance requirements - frequency domain

\begin{center}
  \includegraphics[width=1.0\linewidth]{../../figures/bode-closed-loop-example-responses}
\end{center}

#+BEAMER: \pause

*Activity* What is the gain and phase shift at $\omega = 2$ rad/s?

*** Note                                                           :noexport:

Gain:  0.3
Phase shift: -200 deg

** Performance requirements - frequency domain

\begin{center}
  \includegraphics[width=.8\linewidth]{../../figures/spec-bode-closed-loop-new}
\end{center}


** Performance requirements - frequency domain

 *Activity* Does the system satisfy the requirements?

 
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.7
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/bode-closed-loop-example}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.3
:END:

 | Bandwidth      | >3 rad/s |
 | Resonance peak | <9dB    |



* Problem situation, again                                         :noexport:
** The problem situation, revisited
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

\begin{center}
  \includegraphics[width=.94\linewidth]{../../figures/mars-rover-curiosity-vehicle-cosmos.jpg}
\end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

#+beamer: \pause

- Mass 900 kg
- Six wheels, each with DC motor
- Assuming motors of 20W each, and mechanical efficiency of 90%:
  - How long to accelerate the rover to 1 m/s?
#+beamer: \pause
- Assuming max motor torque of 30 mNm and no loss in transmission.
  - What gear ratio is needed to obtain 6Nm torque on wheel axis?

*** Notes                                                          :noexport:

- Curiosity rover
- Operating on mars for more than 10 years.
- Weighs close to 1t
- Six wheels, each with a DC motor 20W
- 0.9*6*20W = 108W acc 1t to 1 m/s:
  - Ek = 1/2 m v^2 = 0.5 * 900 * 1 = 450 J
  - P = dE/dt => \approx P_max = \Delta E / \Delta T => \Delta T = \Delta E / P_max = 450 J / (108) J/s \approx 4.2s
- P in  = P out, P = T*\omega, T_out * w_out = T_in * w_in => T_out/T_in = w_in/w_out = g_r
  g_r = T_out / T_in = 6 Nm / 30e-3 Nm = 1000 * 6/30 = 100 * 60/30 = 200:1
- 
- 



*  Two-degree of freedom controller                                :noexport:
** The two-degree-of-freedom controller

\begin{center}
  \includegraphics[width=.7\linewidth]{../../figures/2dof-block-complete}
\end{center}

#+BEAMER: \pause

Using the property of /superposition/ of LTIs:
\begin{align*}
Y(s) &= G_c(s)R(s) + S(s)V(s) - T(s)N(s)
\end{align*}

#+BEAMER: \pause

| Closed-loop system (from reference to output) | \(G_c(s) = \frac{G(s)F_f(s)}{1 + G(s)F_b(s)}\) |
| Sensitivity function                          | \(S(s) = \frac{1}{1 + G(s)F_b(s)}\)            |
| Complementary sensitivity function            | \(T(s) = \frac{G(s)F_b(s)}{1 + G(s)F_b(s)}\)   |

** The two-degree-of-freedom controller

\begin{center}
  \includegraphics[width=.5\linewidth]{../../figures/2dof-block-complete}
\end{center}

| Sensitivity function                          | \(S(s) = \frac{1}{1 + G(s)F_b(s)}\)            |
| Complementary sensitivity function            | \(T(s) = \frac{G(s)F_b(s)}{1 + G(s)F_b(s)}\)   |

*Activity* Calculate \(S(s) + T(s) = \)


** The two-degree-of-freedom controller

\begin{center}
  \includegraphics[width=.6\linewidth]{../../figures/2dof-block-complete}
\end{center}

*Why* the two-degrees of freedom controller?

#+BEAMER: \pause

To seperate two design requirements:

1. Obtain desired reference (set-point) tracking.
2. Find good trade-off between disturbance rejection (small \(S(s)\)) and noise attenuation (small \(T(s)\)).


* Proportional control of the DC motor                             :noexport:

** The DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-DC-feedback-white}
    \end{center}
*** Text
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \def\ggain{200}
     \def\Tcnst{0.1}
     \begin{tikzpicture}
       \begin{axis}[
       width=7cm,
       height=6cm,
       grid = both,
       xlabel = {Time [s]},
       ylabel = {Ang vel [rad/s]},
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -0.2, xmax=2,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=-0.2:2, samples=100] {(x>0)*\ggain*(1 - exp(-(x/\Tcnst)))}; 
      \end{axis}
     \end{tikzpicture}
    \end{center}



** The normalized DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-normalized-DC-feedback-white}
    \end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \def\ggain{1}
     \def\Tcnst{1}
     \begin{tikzpicture}
       \begin{axis}[
       width=7cm,
       height=6cm,
       grid = both,
       xlabel = {Time [$\tau$]},
       ylabel = {Ang vel [20 rad/$\tau$], angle [20 rad]},
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -2, xmax=20,
       minor y tick num=9,
       minor x tick num=9,
       every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, green!50!black, no marks, domain=-2:20, samples=100] {(x>0)*\ggain*(1 - exp(-(x/\Tcnst)))};
	 \addplot [thick, red!60!black, no marks, domain=-0.2:5, samples=100] {(x>0)*\ggain*(x + exp(-(x/\Tcnst)) -1)};
       \end{axis}
     \end{tikzpicture}
    \end{center}



** Proportional control of the normalized DC motor

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../../figures/block-DC-feedback}
    \end{center}

*** plot
:PROPERTIES:
:BEAMER_col: 0.5
:END:

    \begin{center}
     \def\ggain{1}
     \def\Tcnst{1}
     \begin{tikzpicture}
       \begin{axis}[
       width=7cm,
       height=6cm,
       grid = both,
       xlabel = {Time [$\tau$]},
       ylabel = {Angle [20 rad]},
       title = {$K=1$},
       %xtick = {0, \tdelay, \tone, \two},
       %xticklabels = {0, $\theta$, $\theta+\frac{\tau}{3}$, $\theta + \tau$},
       %ytick = {0, \yone, \ytwo, \uampl, \yfinal},
       %yticklabels = {0, $0.283y_{f}$, $0.632y_f$, $u_f$, $y_f$},
       xmin = -2, xmax=20,
       minor y tick num=4,
       minor x tick num=4,
       every major grid/.style={red, opacity=0.5},
       ]
	 \addplot [thick, black, no marks, domain=-2:20, samples=200] {x>0};
	 \addplot [thick, red!60!black, no marks, domain=-0.2:20, samples=100] {(x>0)*(1 - (exp(-x/2)* (sqrt(3)* cos(deg((sqrt(3)* x)/2)) + sin(deg((sqrt(3)* x)/2))))/sqrt(3))};
       \end{axis}
     \end{tikzpicture}
    \end{center}


    #+BEAMER: \pause
    *Activity* What is the overshoot (in percent) and rise time (in seconds)?
    
